[package]
name = "Reretty"
version = "0.1.0"
edition = "2021"

[lib]
name = "reretty"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.5.7"
